# Generated by Django 5.0.4 on 2024-04-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogDetails',
            fields=[
                ('log_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=250)),
                ('changes', models.CharField(max_length=250)),
            ],
        ),
    ]
